/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XDR_H_RPCGEN
#define _RPC_XDR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNUMBERS 100

struct rpc_request {
	int count;
};
typedef struct rpc_request rpc_request;

struct rpc_response {
	struct {
		u_int result_len;
		int *result_val;
	} result;
};
typedef struct rpc_response rpc_response;

#define RPC_TEST 0x2000
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GEN_NUMS 1
extern  rpc_response * gen_nums_1(rpc_request *, CLIENT *);
extern  rpc_response * gen_nums_1_svc(rpc_request *, struct svc_req *);
extern int rpc_test_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GEN_NUMS 1
extern  rpc_response * gen_nums_1();
extern  rpc_response * gen_nums_1_svc();
extern int rpc_test_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rpc_request (XDR *, rpc_request*);
extern  bool_t xdr_rpc_response (XDR *, rpc_response*);

#else /* K&R C */
extern bool_t xdr_rpc_request ();
extern bool_t xdr_rpc_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XDR_H_RPCGEN */
