/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_xdr.h"

bool_t
xdr_rpc_request (XDR *xdrs, rpc_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_response (XDR *xdrs, rpc_response *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->result.result_val, (u_int *) &objp->result.result_len, MAXNUMBERS,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
