/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_xdr.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rpc_response *
gen_nums_1(rpc_request *argp, CLIENT *clnt)
{
	static rpc_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GEN_NUMS,
		(xdrproc_t) xdr_rpc_request, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
